### ISSUE TITLE
Smap not found [windows]

### ISSUE THREAD

**Issue by LaFinBuddha** [s0md3v/Smap#10]
```
C:\Users\user>smap
'smap' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\user>smap.exe
'smap.exe' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by bolshoytoster** [comment]
@LaFinBuddha try running `C:/Users/user/go/bin/smap`.

If that works, add `C:/Users/user/go/bin` to your PATH.

If it gives the same error, try running `go install -v github.com/s0md3v/smap/cmd/smap@latest` again.
