### ISSUE TITLE
[Question] Smap display cve

### ISSUE THREAD

**Issue by Anthony-76** [s0md3v/Smap#12]
Hi,

With Nmap, if I use vulners scripts, I can have a possible cve list that permit me to know if my system has a cve not patched.

the following nmap command is: nmap -sV --script vulners <target>

With Smap, is it possible to have the result in order to know actives cve on network/hosts?
If yes, what is the command to execute?

Thank you
Best regars
Anthony

**Comment by s0md3v** [comment]
Use the `-oS` option instead of `--script vulners`.

It is also mentioned in Smap's documentation, if you read it :)

**Comment by spidy0x0** [comment]
> Use the `-oS` option instead of `--script vulners`.
> 
> It is also mentioned in Smap's documentation, if you read it :)

docs has not been referenced anywhere on this repo.

**Comment by s0md3v** [comment]
It is referenced.
![image](https://user-images.githubusercontent.com/26716802/164612140-48996826-e8d3-40c5-8009-abe3c08a7dcd.png)

Please stop treating open source devs as your customer support. We can sell these software but we are giving them away for free - you can at least contribute by reading the docs before creating issues :)
