### ISSUE TITLE
json format -oJ

### ISSUE THREAD

**Issue by anasbousselham** [s0md3v/Smap#17]
Hi,
The  json output format not working.
The file output is empty.

**Comment by s0md3v** [comment]
Can you paste your command here?

**Comment by anasbousselham** [comment]
`smap -iL ip.txt -oJ test.txt`

**Comment by s0md3v** [comment]
I am able to reproduce this issue. It will be fixed soon.
Thanks for reporting :)

**Comment by ssnkhan** [comment]
I can see that the fix has been pushed to the repo, but looks like several months on, homebrew still continues to install `Smap 0.1.0-rc`. Does an update need to be pushed to the homebrew repo too? Many thanks!

**Comment by s0md3v** [comment]
The fix for this has shipped to all package managers. Closing this issue.
