### ISSUE TITLE
Host is up.

### ISSUE THREAD

**Issue by Jorrdannx** [s0md3v/Smap#18]
Hi when running smap with just one target it worked perfectly. Then I tried smap -iL ips.txt and all the results were "Host is up." so I tried again with just one target and now I get no results other than "Host is up."

**Comment by s0md3v** [comment]
I am unable to reproduce this, looks you got rate limited somehow - I will look into it.

**Comment by kz6fittycent** [comment]
same issue here

**Comment by s0md3v** [comment]
Latest version prints a warning when an error like this occurs.
