### ISSUE TITLE
support http proxy

### ISSUE THREAD

**Issue by timwhitez** [s0md3v/Smap#2]
support http proxy

**Comment by s0md3v** [comment]
Why?

**Comment by timwhitez** [comment]
to bypass shodan rate limit

**Comment by s0md3v** [comment]
I have been using this for a month now and I haven't hit a rate limit yet. If you run into it, let me know how to reproduce it and I will think about a proxy option.

PS: If you hit a rate limit while scanning >10k hosts, it doesn't count.
