### ISSUE TITLE
Broken range of /16

### ISSUE THREAD

**Issue by T3jv1l** [s0md3v/Smap#20]
Hello, the tool doesn't know how to scan the range with 192.xxx.x.x/16
![image](https://user-images.githubusercontent.com/33009059/177100599-7cde1955-8b94-4959-86c0-c68de3cfb92b.png)

**Comment by s0md3v** [comment]
Unable to reproduce, please share the exact command. If you have privacy concerns, you can message me on [twitter](https://twitter.com/s0md3v).
![image](https://user-images.githubusercontent.com/26716802/182384849-7f4eaf3f-090e-4f4c-93f6-b4fd69622786.png)
