### ISSUE TITLE
Version string not matching with the release

### ISSUE THREAD

**Issue by b-reich** [s0md3v/Smap#21]
This should be bump to 0.1.11 (better 0.1.12 because the source in the releases doenst include this at the moment)
https://github.com/s0md3v/Smap/blob/5775197d4407ebf24dff0d87b1c8ca9015e420eb/internal/global/variables.go#L35

**Comment by b-reich** [comment]
When you compile the source from the relase this happen
```
❯ smap -h
Smap 0.1.0-rc
```

**Comment by b-reich** [comment]
need this for the release in homebrew

**Comment by b-reich** [comment]
maybe something like this would help 
https://github.com/CycloneDX/cyclonedx-gomod/actions/runs/940383597/workflow

or the logic about the version string in the file is changed..

**Comment by s0md3v** [comment]
Hi @b-reich, this took a while but the Github release is now 0.1.12 with all known bugs fixed.

Please update the homebrew and AUR repos. Thanks!

**Comment by s0md3v** [comment]
Hi @b-reich, were you able to update the repos? In case you are busy with your personal commitments, please transfer the ownership of the packages to me.

**Comment by b-reich** [comment]
@s0md3v homebrew is updating it by itself.
My arch notebook just got a fresh reinstall, a few days ago. Without it I cant update -bin package

I can add you as maintainer for the aur package and gh repo.

https://repology.org/project/smap-shodah-nmap/versions

**Comment by b-reich** [comment]
Sorry, I forgot my gh actions to build publish the aur package. Nevermind can update it without having a arch install here.
