### ISSUE TITLE
result???

### ISSUE THREAD

**Issue by a823883735** [s0md3v/Smap#28]
![image](https://user-images.githubusercontent.com/44701568/217184960-81d0837c-548e-4dcd-93b9-13d98c7b04a7.png)

![image](https://user-images.githubusercontent.com/44701568/217185009-7d646530-07b9-46cf-9e41-588d1edc33d8.png)

**Comment by s0md3v** [comment]
That's a private/local IP address.

**Comment by a823883735** [comment]
> 

Sorry.What's the difference? Why can nmap scan?

**Comment by s0md3v** [comment]
Because smap uses shodan.io

**Comment by a823883735** [comment]
> 

Thank you.
