### ISSUE TITLE
parrot setup

### ISSUE THREAD

**Issue by b4sh1t1** [s0md3v/Smap#5]
Hello,

When we setup the tool it's seems still didn't installed correctly, go installed and confirmed working

 $go version
go version go1.17.8 linux/amd64

sudo go install -v github.com/s0md3v/smap/cmd/smap@latest

result:

smap
bash: smap: command not found

**Comment by s0md3v** [comment]
Why are you installing it with sudo?

If you want to do that, make sure $PATH is set up correctly for the root user.

**Comment by b4sh1t1** [comment]
Sorry i installed it first without sudo and it's installed successfully, later on i try with sudo and same result, and still same issue and path correct.

**Comment by b4sh1t1** [comment]
Do you have TG or qTOX to show you there ?

**Comment by s0md3v** [comment]
Well, you are definitely doing something wrong.

Anyways, this issue is not related to Smap, its related to properly setting up `go` on your system. Google your issue and solve it.

**Comment by b4sh1t1** [comment]
np.

**Comment by b4sh1t1** [comment]
update to fix this issue for other who's intersted in this tool.

to fix this issue you may need to update your go path after install it.

go install -v github.com/s0md3v/smap/cmd/smap@lates
export GOPATH="$HOME/go"
PATH="$GOPATH/bin:$PATH"

@s0md3v would be nice from you to add this into the installation guide.

**Comment by s0md3v** [comment]
If you don't put the PATH inside your `~/.profile` file as suggested in README, it won't work when you restart your terminal ^^
