### ISSUE TITLE
Released on aur

### ISSUE THREAD

**Issue by b-reich** [s0md3v/Smap#6]
Hi, I start maintaining the the aur for smap.

Can be found here: https://aur.archlinux.org/packages/smap-git
Source can be found here: https://github.com/b-reich/aur

This could be referenz in the readme if you like. (I can open the PR)

**Comment by s0md3v** [comment]
Thanks for the AUR package @b-reich.

I can add it to the README myself but it would be better if you do it because that will make you a "contributor" in Smap.

**Comment by b-reich** [comment]
@s0md3v I will create a PR

**Comment by b-reich** [comment]
@s0md3v I can also provide an AUR package which provides the compiled bin.

**Comment by s0md3v** [comment]
@b-reich, it will pull the binary from the latest release right?

Let's have two AUR packages then, `smap-git` for latest stable binary and `smap-git-dev` for compiling the master branch from source.

**Comment by b-reich** [comment]
@s0md3v per convention a `*-git` package always build from source. I will create an `smap` package which use the latest binary.
This would fit in the name convention.

**Comment by b-reich** [comment]
@s0md3v  https://aur.archlinux.org/packages/smap-bin is online
Which deps are required? nmap?

`-bin`is the correct convention for it

**Comment by s0md3v** [comment]
Thanks @b-reich! There are no dependencies.

Btw, why is it `smap-bin` and not `smap`?

**Comment by s0md3v** [comment]
Hi @b-reich, I went through `PKGBUILD` file and turns out it has a hardcoded version.
Shouldn't it fetch the latest version automatically?

**Comment by b-reich** [comment]
@s0md3v I was wrong...
`smap` should build from tag (0.1.0)
`smap-bin` uses precompiled  bins
`smap-git` build from master/develop (depends on the git/branch flow)

**Comment by s0md3v** [comment]
Hi @b-reich, I went through PKGBUILD file and turns out it has a hardcoded version number.
Shouldn't it fetch the latest version automatically?

**Comment by b-reich** [comment]
> Hi @b-reich, I went through `PKGBUILD` file and turns out it has a hardcoded version. Shouldn't it fetch the latest version automatically?

Precompiled should updated by hands, the checksum are also updated by hand. I think this is correct in this form. - I have to update every release by hand.
